### PR TITLE
Refactor to remove action layout from DataLayer and use block instead

### PR DESCRIPTION
**Pull request by PascalNoisette**
Please considered this refactoring to improve Model\DataLayer source code :
* full action name verification such as `if($this->fullActionName === 'checkout_index_index'){` is a mecanism that is natively handled by layouts files. You do not need to do it.
* a single model class is responsible for several data extraction tasks (customer session, product data, category data...). One class per task is preferable.
* 250 lines long file/6 parameters constructor are hard to read
* MagePal\GoogleTagManager\Block\Tm::addVariable can be called by other block of the layout

### CODE REVIEW

**Comment by srenon** [comment]
@PascalNoisett ... nice work, you seem to address most of the issue I wanted to fix.

Give me a few days to merge because I want to add JS layer to push all the customer/cart that full page cache strip out.

Thanks for your PR

**Comment by PascalNoisette** [comment]
@srenon thanks for your feedback. I tried to address the fpc issue in [the other branch](https://github.com/PascalNoisette/magento2-googletagmanager/tree/use_async_gtm) using the [section concept](http://devdocs.magento.com/guides/v2.0/config-guide/cache/cache-priv-priv.html). There was already [cart ](https://github.com/PascalNoisette/magento2-googletagmanager/blob/af9cdf90c124bbf58d55c2f50e50801458dca50a/view/frontend/web/js/cart.js)and [customer](https://github.com/PascalNoisette/magento2-googletagmanager/blob/af9cdf90c124bbf58d55c2f50e50801458dca50a/view/frontend/web/js/customer.js) data available for our purpose. I did not dare to PR because googletagmanager documentation recommend to add gtm.js  _"as close to the opening `<head>` tag as possible"_ while session data coming from ["customer" and "cart" section] are available way later in the process (they depend on requirejs loading).  That would delay and condition gtm.js inclusion, I do not know what are the risks, do you want a merge request for this anyway ?

Regards, Pascal Noisette

**Comment by srenon** [comment]
@PascalNoisette .... my idea was to keep it as is with the datalayer as close to the top as possible, then use datalayer.push(jsCustomerObject). 

Then in GTM if want to know if a customer is login or if a customer cart has item, you could use `gtm.load` and all the variables should be there

**Comment by srenon** [comment]
@PascalNoisette ... FYI "section data" only get update after a post or invalidate 

e.g https://github.com/magento/magento2/issues/6745

**Comment by srenon** [comment]
@PascalNoisette ... thanks for the PR. I build upon your code and integrate the js layer

**Pull request closed without merging**
